package com.tgchatmonitor.app

import java.io.File

object EnvStore {
    private val keys = listOf(
        "BOT_TOKEN",
        "API_ID",
        "API_HASH",
        "ADMIN_USER_ID",
        "TELETHON_SESSION",
        "DATABASE_URL",
        "POLL_INTERVAL",
        "SCAN_PERIOD_DAYS",
        "SCAN_HISTORY_LIMIT",
        "SCAN_MODE",
        "TELEGRAM_NOTIFY",
    )

    fun envFile(dataDir: File): File = File(dataDir, ".env")

    fun isConfigured(dataDir: File): Boolean {
        val values = load(dataDir)
        return listOf("API_ID", "API_HASH").all { !values[it].isNullOrBlank() }
    }

    fun load(dataDir: File): MutableMap<String, String> {
        val result = mutableMapOf(
            "TELETHON_SESSION" to "monitor_session",
            "DATABASE_URL" to "sqlite+aiosqlite:///./monitor.db",
            "POLL_INTERVAL" to "10",
            "SCAN_PERIOD_DAYS" to "7",
            "SCAN_HISTORY_LIMIT" to "100",
            "SCAN_MODE" to "timeline",
            "TELEGRAM_NOTIFY" to "0",
        )
        val file = envFile(dataDir)
        if (!file.exists()) return result

        file.readLines(Charsets.UTF_8).forEach { line ->
            val trimmed = line.trim()
            if (trimmed.isEmpty() || trimmed.startsWith("#") || "=" !in trimmed) return@forEach
            val (key, value) = trimmed.split("=", limit = 2)
            result[key.trim()] = value.trim()
        }
        return result
    }

    fun save(dataDir: File, values: Map<String, String>) {
        dataDir.mkdirs()
        val merged = load(dataDir)
        merged.putAll(values.mapValues { it.value.trim() })
        val lines = buildList {
            add("# Generated by TG Chat Monitor Android app")
            keys.forEach { key ->
                val value = merged[key]?.trim().orEmpty()
                if (value.isNotEmpty() || key in setOf(
                        "TELETHON_SESSION",
                        "DATABASE_URL",
                        "POLL_INTERVAL",
                        "SCAN_PERIOD_DAYS",
                        "SCAN_HISTORY_LIMIT",
                        "SCAN_MODE",
                        "TELEGRAM_NOTIFY",
                    )
                ) {
                    add("$key=$value")
                }
            }
        }
        envFile(dataDir).writeText(lines.joinToString("\n") + "\n", Charsets.UTF_8)
    }
}
